### ISSUE TITLE
Sidebar background-color

### ISSUE THREAD

**Issue by notshi** [codeforIATI/sidebar#4]
Thanks very much for creating this! Having a sidebar for all CFI projects is a great idea and it's so much easier to move around projects (@xriss refers to it as a dropdown webring).

Just wondering about the decision for the background-color - it seems a bit dark and jarring from the rest of the sites on CFI (unless there are plans for a rebranding I missed, apoloogies).

![sidebar](https://user-images.githubusercontent.com/1515961/121552795-a6af7d80-ca08-11eb-8bd4-75f445fb01b6.png)

I did a mock up using the colours on the CFI homepage and it feels cleaner and lighter so it's easier to read.

The changes I did are as follows on https://github.com/codeforIATI/sidebar/blob/main/sidebar.scss#L8:
```
$c4i_bg_color: #ececec;
$c4i_fg_color: #212529;
```
Happy to do a pr but it looks like the code change also affects the box-shadow and hover states and at present, am unable to test this locally - could you tell me what I'm missing / need to install?

**Comment by andylolz** [comment]
> unable to test this locally - could you tell me what I'm missing / need to install?

Eek – apologies. I’ve added the missing Gemfile, and also some instructions in the README.

These colours look great – I’ve pushed the change in 3455babe.

**Comment by andylolz** [comment]
> unable to test this locally - could you tell me what I'm missing / need to install?

Eek – apologies. I’ve added the missing Gemfile, and also some instructions in the README.

These colours look great – thanks! I’ve pushed the change in 3455babe.

**Comment by andylolz** [comment]
Btw I should add: this repo is a first pass. Very happy to accept PRs for anything here, really. The dev setup is probably still not ideal, so let me know if you have any problems and I’ll try to improve it!

**Comment by andylolz** [comment]
Amazing! It looks great!
