### ISSUE TITLE
Dev setup

### ISSUE THREAD

**Issue by notshi** [codeforIATI/sidebar#5]
Tried running locally and faced a couple of issues which I'm bringing up here so it might help someone else.

The current instructions were very handy (thank you!) but when I ran the dev server, the sidebar button didn't work so I thought building the project might wake it up.

Running `./build.sh` gave me this error

    ./build.sh: line 3: ./node_modules/uglify-js/bin/uglifyjs: No such file or directory

So I ran `npm install`  

    added 2 packages from 3 contributors and audited 2 packages in 0.916s

That seems to have fixed it as the button now works locally.

**Comment by andylolz** [comment]
Ohhh… You’re absolutely right. Forgot about this. I’ll add it to the instructions now.

**Comment by andylolz** [comment]
Fixed in 9cedca8.
